// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// updateBeta
List updateBeta(arma::mat Theta, arma::mat B0, double lamB, double eta, double tolin, int maxitrin, const List& info);
RcppExport SEXP _missoNet_updateBeta(SEXP ThetaSEXP, SEXP B0SEXP, SEXP lamBSEXP, SEXP etaSEXP, SEXP tolinSEXP, SEXP maxitrinSEXP, SEXP infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< double >::type lamB(lamBSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type tolin(tolinSEXP);
    Rcpp::traits::input_parameter< int >::type maxitrin(maxitrinSEXP);
    Rcpp::traits::input_parameter< const List& >::type info(infoSEXP);
    rcpp_result_gen = Rcpp::wrap(updateBeta(Theta, B0, lamB, eta, tolin, maxitrin, info));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_missoNet_updateBeta", (DL_FUNC) &_missoNet_updateBeta, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_missoNet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
