// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// updateBeta
List updateBeta(const arma::mat& Theta, arma::mat& B0, const int& n, const arma::mat& xtx, const arma::mat& xty, const double& lamB, const double& eta, const double& tolin, const int& maxitrin);
RcppExport SEXP _missoNet_updateBeta(SEXP ThetaSEXP, SEXP B0SEXP, SEXP nSEXP, SEXP xtxSEXP, SEXP xtySEXP, SEXP lamBSEXP, SEXP etaSEXP, SEXP tolinSEXP, SEXP maxitrinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xtx(xtxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xty(xtySEXP);
    Rcpp::traits::input_parameter< const double& >::type lamB(lamBSEXP);
    Rcpp::traits::input_parameter< const double& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double& >::type tolin(tolinSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxitrin(maxitrinSEXP);
    rcpp_result_gen = Rcpp::wrap(updateBeta(Theta, B0, n, xtx, xty, lamB, eta, tolin, maxitrin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_missoNet_updateBeta", (DL_FUNC) &_missoNet_updateBeta, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_missoNet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
