# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateBeta <- function(Theta, B0, n, xtx, xty, lamB, eta, tolin, maxitrin) {
    .Call(`_missoNet_updateBeta`, Theta, B0, n, xtx, xty, lamB, eta, tolin, maxitrin)
}

